export const commentsPage = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Facebook Comment operations · Stopirex</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#18212f;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}.tab{padding:10px 14px;border-radius:10px;text-decoration:none;color:#334155;background:#fff}.tab.active{color:#fff;background:#334155}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.muted{color:#64748b}.grid{display:grid;gap:14px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:16px}.row{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.badges{display:flex;gap:6px;flex-wrap:wrap}.badge{font-size:12px;padding:4px 8px;border-radius:999px;background:#e2e8f0}.urgent,.failed{background:#fee2e2;color:#991b1b}.hide{background:#fef3c7;color:#92400e}.reply{border-left:3px solid #cbd5e1;padding-left:12px;margin-top:12px;white-space:pre-wrap}.actions button,.head button{border:0;border-radius:8px;padding:9px 13px;cursor:pointer;background:#334155;color:#fff}.empty{text-align:center;padding:48px;color:#64748b}.review{padding:14px 16px;border:1px solid #c7d2fe;border-radius:12px;margin-bottom:16px;background:#eef2ff}.review strong{color:#3730a3}@media(max-width:700px){.row{display:block}.actions{margin-top:12px}.head{align-items:flex-start}}
</style>
</head><body><main class="wrap">
<nav class="tabs"><a class="tab" href="/operations">Operations</a><a class="tab" href="/orders">Orders</a><a class="tab active" href="/comments?review=1">Comment operations</a><a class="tab" href="/product">Product knowledge</a><a class="tab" href="/pages?review=1">Page administration</a></nav>
<div class="head"><div><h1>Facebook Comment operations</h1><p class="muted">Public replies, one private follow-up and privacy-safe moderation. / Quản lý trả lời công khai, inbox riêng và bảo vệ thông tin khách.</p></div><button onclick="load()">Refresh</button></div>
<section id="reviewGuide" class="review" hidden><strong>Reviewer evidence:</strong> create a new comment on the supplied review post, wait for the public and private replies, then find that event below. Use a dummy contact-information comment to demonstrate Hide/Unhide. Genuine complaints without personal information remain visible.</section>
<section id="list" class="grid"><div class="empty">Loading comments…</div></section>
</main><script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=v=>v?new Date(v).toLocaleString('en-GB'):'';
if(new URLSearchParams(location.search).get('review')==='1')document.getElementById('reviewGuide').hidden=false;
async function setVisibility(id,hidden){const r=await fetch('/api/meta/comments/'+id+'/visibility',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({hidden})});if(!r.ok){alert('The comment visibility could not be updated.');return}await load()}
function card(x){return '<article class="card"><div class="row"><div><div class="badges"><span class="badge">'+esc(x.pageName)+'</span><span class="badge '+(x.priority==='urgent'?'urgent':'')+'">'+esc(x.category)+'</span><span class="badge '+(x.status==='failed'?'failed':'')+'">'+esc(x.status)+'</span>'+(x.moderationRecommendation!=='keep'?'<span class="badge hide">Privacy action: '+esc(x.moderationRecommendation)+'</span>':'')+'</div><h3>'+esc(x.commentText)+'</h3><div class="muted">Received '+time(x.receivedAt)+'</div></div><div class="actions"><button onclick="setVisibility(&quot;'+esc(x.id)+'&quot;,'+(!x.isHidden)+')">'+(x.isHidden?'Unhide comment':'Hide comment')+'</button></div></div>'+(x.moderationReason?'<p class="muted">Moderation reason: '+esc(x.moderationReason)+'</p>':'')+(x.publicReplyText?'<div class="reply"><b>Public reply</b><br>'+esc(x.publicReplyText)+'</div>':'')+(x.privateReplyText?'<div class="reply"><b>Private reply</b><br>'+esc(x.privateReplyText)+'</div>':'')+'</article>'}
async function load(){const root=document.getElementById('list');try{const r=await fetch('/api/meta/comments');const j=await r.json();if(!r.ok)throw new Error(j.error||'request_failed');root.innerHTML=j.length?j.map(card).join(''):'<div class="empty">No Page comments have been received yet.</div>'}catch{root.innerHTML='<div class="empty">Comment data could not be loaded.</div>'}}
load();
</script></body></html>`;
