export const pagesPage = `<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fanpage · Stopirex</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#18212f;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}.tab{padding:10px 14px;border-radius:10px;text-decoration:none;color:#334155;background:#fff}.tab.active{color:#fff;background:#334155}.grid{display:grid;grid-template-columns:1.7fr 1fr;gap:16px}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:20px}.page{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid #e2e8f0}.muted{color:#64748b;font-size:13px}.button{display:block;text-align:center;padding:11px 14px;border:0;border-radius:10px;text-decoration:none;background:#2459d3;color:#fff;font-weight:700}.switch{width:44px;height:24px}.notice{padding:10px;border-radius:9px;margin-bottom:12px;background:#e8f5ee;color:#176b46}.error{background:#fee2e2;color:#991b1b}@media(max-width:750px){.grid{grid-template-columns:1fr}}
</style></head><body><main class="wrap">
<nav class="tabs"><a class="tab" href="/operations">Tổng quan</a><a class="tab" href="/orders">Đơn hàng</a><a class="tab" href="/comments">Bình luận</a><a class="tab" href="/product">Sản phẩm</a><a class="tab active" href="/pages">Fanpage</a></nav>
<h1>Quản trị Fanpage</h1><p class="muted">Kết nối Page qua Facebook OAuth và bật bot riêng cho đúng Page cần vận hành.</p>
<div id="result"></div><div class="grid"><section class="panel"><h2>Page đã liên kết</h2><div id="pages">Đang tải…</div></section>
<aside class="panel"><h2>Kết nối bằng Facebook</h2><p class="muted">Đăng nhập Facebook, cấp quyền và chọn Page. Page Token được mã hóa trước khi lưu.</p><a class="button" href="/api/meta/oauth/start">Đăng nhập bằng Facebook</a><p class="muted">Page mới mặc định tắt bot. Sau khi kết nối, chỉ bật đúng Page cần sử dụng.</p></aside></div>
<script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function toggle(id,enabled){const r=await fetch('/api/meta/pages/'+id+'/bot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enabled})});if(!r.ok)alert('Không cập nhật được Page');await load()}
async function load(){const r=await fetch('/api/meta/pages');const root=document.getElementById('pages');if(!r.ok){root.textContent='Chưa cấu hình quản lý Page';return}const list=await r.json();root.innerHTML=list.length?list.map(x=>'<div class="page"><div><b>'+esc(x.displayName)+'</b><div class="muted">ID '+esc(x.externalPageId)+' · '+(x.credentialConfigured?'Đã kết nối an toàn':'Thiếu token')+'</div></div><input class="switch" type="checkbox" '+(x.botEnabled?'checked ':'')+(!x.credentialConfigured?'disabled ':'')+'onchange="toggle(&quot;'+esc(x.id)+'&quot;,this.checked)"></div>').join(''):'Chưa có Page nào.'}
const p=new URLSearchParams(location.search),status=p.get('oauth'),count=p.get('count');if(status){const ok=status==='success';document.getElementById('result').innerHTML='<div class="notice '+(ok?'':'error')+'">'+(ok?'Đã kết nối '+esc(count)+' Page. Hãy bật đúng Page cần dùng bot.':'Kết nối Facebook chưa thành công: '+esc(status))+'</div>'}load();
</script></main></body></html>`;
