export const pagesPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Facebook Page administration · Stopirex</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#18212f;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1180px;margin:auto;padding:24px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:20px}.tab{padding:10px 14px;border-radius:10px;text-decoration:none;color:#334155;background:#fff}.tab.active{color:#fff;background:#334155}.grid{display:grid;grid-template-columns:1.7fr 1fr;gap:16px}.panel{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:20px}.page{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:16px 0;border-bottom:1px solid #e2e8f0}.page:last-child{border-bottom:0}.muted{color:#64748b;font-size:13px}.button{display:block;text-align:center;padding:11px 14px;border:0;border-radius:10px;text-decoration:none;background:#2459d3;color:#fff;font-weight:700}.secondary{background:#eef2ff;color:#334155;margin-top:8px}.switch{width:46px;height:26px}.notice{padding:12px 14px;border-radius:9px;margin-bottom:12px;background:#e8f5ee;color:#176b46}.error{background:#fee2e2;color:#991b1b}.review{padding:16px 18px;border:1px solid #c7d2fe;border-radius:14px;margin-bottom:16px;background:#eef2ff}.review h2{margin:0 0 8px}.review ol{margin-bottom:0;padding-left:22px}.review li{margin:7px 0}.status{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.badge{padding:4px 8px;border-radius:999px;background:#e2e8f0;font-size:12px}.ok{background:#dcfce7;color:#166534}.off{background:#fef3c7;color:#92400e}.permissions{padding-left:18px;font-size:13px;line-height:1.6}code{background:#f1f5f9;border-radius:5px;padding:2px 4px}@media(max-width:750px){.grid{grid-template-columns:1fr}.page{align-items:flex-start}}
</style></head><body><main class="wrap">
<nav class="tabs"><a class="tab" href="/operations">Operations</a><a class="tab" href="/orders">Orders</a><a class="tab" href="/comments?review=1">Comment operations</a><a class="tab" href="/product">Product knowledge</a><a class="tab active" href="/pages?review=1">Page administration</a></nav>
<h1>Facebook Page administration</h1><p class="muted">Connect only Pages administered by the signed-in user, then enable automation separately for each Page. / Kết nối và bật bot riêng cho từng Fanpage.</p>
<section id="reviewGuide" class="review" hidden><h2>Meta reviewer flow</h2><ol><li>Select <strong>Connect with Facebook</strong> and show the complete Facebook Login permission screen.</li><li>Grant the requested Page permissions and select the supplied review Page.</li><li>Return here and show the encrypted credential and webhook subscription badges.</li><li>Enable automation, then test one Messenger message and one Page comment.</li><li>Open <strong>Comment operations</strong> to show the public reply, private reply and moderation action.</li></ol></section>
<div id="result"></div><div class="grid"><section class="panel"><h2>Connected Pages</h2><p class="muted"><code>pages_show_list</code> limits this list to Pages managed by the administrator.</p><div id="pages">Loading…</div></section>
<aside class="panel"><h2>Connect with Facebook</h2><p>Use the visible Facebook Login flow to grant Page permissions and choose a managed Page.</p><a class="button" href="/api/meta/oauth/start">Connect with Facebook</a><a class="button secondary" href="/comments?review=1">Open Comment operations</a><p class="muted">Page tokens are encrypted before storage and are never displayed. A newly connected Page is disabled until the administrator explicitly enables it.</p><h3>Requested permissions</h3><ul class="permissions"><li><code>pages_show_list</code></li><li><code>pages_manage_metadata</code></li><li><code>pages_messaging</code></li><li><code>pages_read_user_content</code></li><li><code>pages_read_engagement</code></li><li><code>pages_manage_engagement</code></li></ul></aside></div>
<script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);if(params.get('review')==='1')document.getElementById('reviewGuide').hidden=false;
async function toggle(id,enabled){const r=await fetch('/api/meta/pages/'+id+'/bot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({enabled})});if(!r.ok)alert('The Page automation setting could not be updated.');await load()}
function pageCard(x){const connected=x.credentialConfigured;return '<div class="page"><div><b>'+esc(x.displayName)+'</b><div class="muted">Page ID '+esc(x.externalPageId)+'</div><div class="status"><span class="badge '+(connected?'ok':'off')+'">'+(connected?'Credential encrypted':'Credential missing')+'</span><span class="badge '+(connected?'ok':'off')+'">'+(connected?'Webhook: messages + feed':'Webhook unavailable')+'</span><span class="badge '+(x.botEnabled?'ok':'off')+'">Automation '+(x.botEnabled?'enabled':'disabled')+'</span></div></div><label><span class="muted">Enable bot</span><br><input aria-label="Enable automation for '+esc(x.displayName)+'" class="switch" type="checkbox" '+(x.botEnabled?'checked ':'')+(!connected?'disabled ':'')+'onchange="toggle(&quot;'+esc(x.id)+'&quot;,this.checked)"></label></div>'}
async function load(){const r=await fetch('/api/meta/pages');const root=document.getElementById('pages');if(!r.ok){root.textContent='Page management is not configured.';return}const list=await r.json();root.innerHTML=list.length?list.map(pageCard).join(''):'No Pages connected yet.'}
const status=params.get('oauth'),count=params.get('count');if(status){const ok=status==='success';document.getElementById('result').innerHTML='<div class="notice '+(ok?'':'error')+'">'+(ok?'Connected '+esc(count)+' Page(s). Enable only the Page used for this review.':'Facebook connection failed: '+esc(status))+'</div>'}load();
</script></main></body></html>`;
